src/Entity/Comments.php
<?php

namespace App\Entity;

use App\Repository\CommentsRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CommentsRepository::class)
 */
class Comments
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text")
     */
    private $text;

    /**
     * @ORM\Column(type="boolean")
     */
    private $like_comment;

    /**
     * @ORM\Column(type="integer")
     */
    private $id_comment_parent;

    /**
     * @ORM\ManyToOne(targetEntity=Posts::class, inversedBy="comments")
     * @ORM\JoinColumn(nullable=false)
     */
    private $id_post;

    /**
     * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="comments")
     * @ORM\JoinColumn(nullable=false)
     */
    private $id_user;

    /**
     * @ORM\ManyToOne(targetEntity=NotifComments::class, inversedBy="id_comment")
     * @ORM\JoinColumn(nullable=false)
     */
    private $notifComments;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getText(): ?string
    {
        return $this->text;
    }

    public function setText(string $text): self
    {
        $this->text = $text;

        return $this;
    }

    public function getLikeComment(): ?bool
    {
        return $this->like_comment;
    }

    public function setLikeComment(bool $like_comment): self
    {
        $this->like_comment = $like_comment;

        return $this;
    }

    public function getIdCommentParent(): ?int
    {
        return $this->id_comment_parent;
    }

    public function setIdCommentParent(int $id_comment_parent): self
    {
        $this->id_comment_parent = $id_comment_parent;

        return $this;
    }

    public function getIdPost()
    {
        return $this->id_post;
    }

    public function setIdPost($id_post): self
    {
        $this->id_post = $id_post;

        return $this;
    }

    public function getIdUser()
    {
        return $this->id_user;
    }

    public function setIdUser( $id_user): self
    {
        $this->id_user = $id_user;

        return $this;
    }

    public function getNotifComments(): ?NotifComments
    {
        return $this->notifComments;
    }

    public function setNotifComments(?NotifComments $notifComments): self
    {
        $this->notifComments = $notifComments;

        return $this;
    }
}

src/Form/CommentsType.php
<?php

namespace App\Form;

use App\Entity\Comments;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CommentsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('text')
            ->add('like_comment')
            ->add('id_comment_parent')
            ->add('id_post')
            ->add('id_user')
            ->add('notifComments')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Comments::class,
        ]);
    }
}

src/Controller/CommentsController.php
<?php

namespace App\Controller;

use App\Entity\Posts;
use App\Entity\Comments;
use App\Form\CommentsType;
use App\Repository\PostsRepository;
use App\Repository\UsersRepository;
use App\Repository\CommentsRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

/**
 * @Route("/comments")
 */
class CommentsController extends AbstractController
{
    /**
     * @Route("/", name="comments_index", methods={"GET"})
     */
    public function index(CommentsRepository $commentsRepository): Response
    {
        return $this->render('comments/index.html.twig', [
            'comments' => $commentsRepository->findAll(),
        ]);
    }

    /**
     * @Route("/{username}/new", name="comments_new", methods={"GET","POST"})
     */
    public function new(Request $request, PostsRepository $postsrepository, UsersRepository $usersrepository): Response
    {
        $comment = new Comments();
        
        $username = $request->attributes->get('username');

        $text = $request->request->get('comment_text');

        $id_post_input = $request->request->get('post_id');
        $id_post = $postsrepository->find($id_post_input);

        $id_user_input = $request->request->get('user_id');
        $id_user = $usersrepository->find($id_user_input);

        $comment->setText($text); 
        $comment->setLikeComment(0);
        $comment->setIdPost($id_post);
        $comment->setIdUser($id_user);

        if ($text != "") {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($comment);
            $entityManager->flush();

            return $this->redirectToRoute('home', ['username' => $username], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('posts/new.html.twig', [
            'comments' => $comment,
            
        ]);

    }

    /**
     * @Route("/{id}", name="comments_show", methods={"GET"})
     */
    public function show(Comments $comment): Response
    {
        return $this->render('comments/show.html.twig', [
            'comment' => $comment,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="comments_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Comments $comment): Response
    {
        $form = $this->createForm(CommentsType::class, $comment);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('comments_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('comments/edit.html.twig', [
            'comment' => $comment,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="comments_delete", methods={"POST"})
     */
    public function delete(Request $request, Comments $comment): Response
    {
        if ($this->isCsrfTokenValid('delete'.$comment->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($comment);
            $entityManager->flush();
        }

        return $this->redirectToRoute('comments_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/comments/_delete_form.html.twig
<form method="post" action="{{ path('comments_delete', {'id': comment.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ comment.id) }}">
    <button class="btn">Delete</button>
</form>

templates/comments/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Comments{% endblock %}

{% block body %}
    <h1>Edit Comments</h1>

    {{ include('comments/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('comments_index') }}">back to list</a>

    {{ include('comments/_delete_form.html.twig') }}
{% endblock %}

templates/comments/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Comments index{% endblock %}

{% block body %}
    <h1>Comments index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Text</th>
                <th>Like_comment</th>
                <th>Id_comment_parent</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for comment in comments %}
            <tr>
                <td>{{ comment.id }}</td>
                <td>{{ comment.text }}</td>
                <td>{{ comment.likeComment ? 'Yes' : 'No' }}</td>
                <td>{{ comment.idCommentParent }}</td>
                <td>
                    <a href="{{ path('comments_show', {'id': comment.id}) }}">show</a>
                    <a href="{{ path('comments_edit', {'id': comment.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('comments_new') }}">Create new</a>
{% endblock %}

templates/comments/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Comments{% endblock %}

{% block body %}
    <h1>Create new Comments</h1>

    {{ include('comments/_form.html.twig') }}

    <a href="{{ path('comments_index') }}">back to list</a>
{% endblock %}

templates/comments/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Comments{% endblock %}

{% block body %}
    <h1>Comments</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ comment.id }}</td>
            </tr>
            <tr>
                <th>Text</th>
                <td>{{ comment.text }}</td>
            </tr>
            <tr>
                <th>Like_comment</th>
                <td>{{ comment.likeComment ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Id_comment_parent</th>
                <td>{{ comment.idCommentParent }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('comments_index') }}">back to list</a>

    <a href="{{ path('comments_edit', {'id': comment.id}) }}">edit</a>

    {{ include('comments/_delete_form.html.twig') }}
{% endblock %}